version: "3"
services:
  backend:
    container_name: week10
    build:
      context: ../week10
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    restart: always
    depends_on:
      - custommysql
    environment: # Pass environment variables to the service
      SPRING_DATASOURCE_URL: jdbc:mysql://custommysql:3306/week10
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend

  custommysql:
    container_name: custommysql
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: week10
      MYSQL_USER: root
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
    networks:
      - backend


volumes:
  dbdata:
    driver: local

networks:
  backend:
    driver: bridge